<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'School Transportations' => 'Σχολικές Μετακινήσεις',
    'View Transportations' => 'Προβολή Μετακινήσεων',
    'Create Transportation' => 'Δημιουργία Μετακίνησης',
    'Update Transportation' => 'Επεξεργασία Μετακίνησης',
    'View Transportation' => 'Προβολή Μετακίνησης',
    'Update' => 'Ενημέρωση',
    'Create' => 'Δημιουργία',
    'School Units' => 'Σχολικές Μονάδες',
    'View/create/edit/delete transportations' => 'Προβολή/δημιουργία/επεξεργασία/διαγραφή μετακινήσεων',
    'Create a new transportation for a school unit' => 'Δημιουργία νέας μετακίνησης σχολικής μονάδας',
    'Create School Unit' => 'Δημιουργία Σχολικής Μονάδας',
    'Directorate of Education' => 'Διεύθυνση Εκπαίδευσης',
    'Failure in creating school unit' => 'Αποτυχία δημιουργίας σχολικής μονάδας',
    'The school unit was created successfully' => 'Η σχολική μονάδα δημιουργήθηκε επιτυχώς',
    'Update school unit' => 'Ενημέρωση σχολικής μονάδας',
    'The school unit was updated successfully' => 'Η σχολική μονάδα ενημερώθηκε επιτυχώς',
    'Failure in updating school unit' => 'Αποτυχία ενημέρωσης σχολικής μονάδας',
    'Failure in deleting school unit' => 'Αποτυχία διαγραφής της σχολικής μονάδας',
    'The school unit was deleted successfully' => 'Η σχολική μονάδα διαγράφηκε επιτυχώς',
    'Failure in creating the school transportation.' => 'Αποτυχία δημιουργίας της σχολικής μετακίνησης.',
    'The school transport was created successfully.' => 'Η σχολική μετακίνηση δημιουργήθηκε επιτυχώς.',
    'The school transport was deleted successfully.' => 'Η σχολική μετακίνηση διαγράφηκε επιτυχώς.',
    'The school transport was updated successfully.' => 'Η σχολική μετακίνηση ενημερώθηκε επιτυχώς.',
    'Failure in deleting the school transport.' => 'Αποτυχία διαγραφής της σχολικής μετακίνησης.',
    'Failure in deleting the school transport, because it is not in initial state.' => 'Αποτυχία διαγραφής της σχολικής μετακίνησης, επειδή δεν είναι σε αρχική κατάσταση.',
    'School Unit' => 'Σχολείο',
    'Transportation Country' => 'Χώρα',
    'Transportation City' => 'Πόλη',
    'Transportation Start' => 'Έναρξη Μετακίνησης',
    'Transportation End' => 'Λήξη Μετακίνησης',
    'Meeting Start' => 'Έναρξη Συνάντησης',
    'Meeting End' => 'Λήξη Συνάντησης',
    'Head Teacher' => 'Αρχηγός Συνοδός',
    'Transportation Teachers' => 'Μετακινούμενοι/Συνοδοί Εκπαιδευτικοί',
    'Transportation Students' => 'Μετακινούμενοι Μαθητές',
    'The schools\' details were updated in the database.' => 'Τα στοιχεία των σχολείων ενημερώθηκαν στη βάση δεδομένων.',
    'Update School Units Details' => 'Ενημέρωση Στοιχείων Σχολείων',
    'Digital Signed File' => 'Αρχείο Ψηφιακά Υπογεγραμμένο',
    'Approval File' => 'Αρχείο Έγκρισης',
    'Registration Completion Protocol' => 'Ξεχρέωση Πρωτοκόλλου',
    'Approval Sent Date' => 'Αποστολή Έγκρισης',
    'Remarks' => 'Παρατηρήσεις',
    'Approval Document Protocol' => 'Πρωτόκολλο Έγκρισης ΠΔΕ',
    'School Directorate Protocol' => 'Πρωτόκολλο Διεύθυνσης Σχολείου',
    'School Record' => 'Πρακτικό Συλλόγου',
    'Class' => 'Τάξη ή Τμήμα',
    'Program' => 'Πρόγραμμα',
    'Date' => 'Ημερομηνία',
    'Description' => 'Σημείωση',
    'Forward State' => 'Προώθηση Κατάστασης',
    'Update State' => 'Ενημέρωση Κατάστασης',
    'Forward to State' => 'Προώθηση στην Κατάσταση',
    'Update of State' => 'Ενημέρωση της Κατάστασης ',
    'State' => 'Κατάσταση',
    'Download Decision' => 'Κατέβασμα Απόφασης',
    'Forward to next state' => 'Προώθηση στην επόμενη κατάσταση',
    'Backward to previous state' => 'Μετάβαση στην προηγούμενη κατάσταση',
    'View/edit states of a transportation approval' => 'Προβολή/επεξεργασία καταστάσεων διεκπεραίωσης έγκρισης μετακίνησης',
    'Transportation Approval States' => 'Καταστάσεις Διεκπεραίωσης Εγκρίσεων',
    'Transport Approval States' => 'Καταστάσεις Έκρισης Μετακίνησης',
    'The state was updated successfully.' => 'Η κατάσταση της έγκρισης μετακίνσης ενημερώθηκε επιτυχώς.',
    'View States' => 'Καταστάσεις Έγκρισης Μετακίνησης',
    'Update State Title' => 'Ενημέρωση Κατάστασης Έγκρισης',
    'State Name' => 'Τίτλος Κατάστασης Έγκρισης',
    'The transport\'s approval state changed successfully.' => 'Η κατάσταση της έγκρισης μετακίνησης άλλαξε επιτυχώς.',
    'Are you sure you want to change the state of the transport\'s approval?' => 'Είστε σίγουρος/η ότι θέλετε να αλλάξετε την κατάσταση της έγκρισης μετακίνησης;',
    'Transportations Approvals' => 'Εγκρίσεις Μετακινήσεων',
    'View school units as retrieved from myschool' => 'Προβολή σχολικών μονάδων έτσι όπως έχουν αντληθεί από το myschool.',
    'The school transport cannot be updated, because it is not in initial state.' => 'Τα στοιχεία της μετακίνησης δεν μπορούν να αλλάξουν, διότι δεν είναι σε αρχική κατάσταση.'
];
