<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'School Transportations' => 'Μετακινήσεις Σχολείων',
    'View Transportations' => 'Προβολή Μετακινήσεων',
    'Create Transportation' => 'Δημιουργία Μετακίνησης',
    'School Units' => 'Σχολικές Μονάδες',
    'View/edit/delete transportations' => 'Προβολή/επεξεργασία/διαγραφή μετακινήσεων',
    'Create a new transportation for a school unit' => 'Δημιουργία νέας μετακίνησης σχολικής μονάδας',
    'View/edit/delete school units' => 'Προβολή/επεξεργασία/διαγραφή σχολικών μονάδων',
    'Create School Unit' => 'Δημιουργία Σχολικής Μονάδας',
    'Directorate of Education' => 'Διεύθυνση Εκπαίδευσης',
    'Failure in creating school unit' => 'Αποτυχία δημιουργίας σχολικής μονάδας',
    'The school unit was created successfully' => 'Η σχολική μονάδα δημιουργήθηκε επιτυχώς',
    'Update school unit' => 'Ενημέρωση σχολικής μονάδας',
    'The school unit was updated successfully' => 'Η σχολική μονάδα ενημερώθηκε επιτυχώς',
    'Failure in updating school unit' => 'Αποτυχία ενημέρωσης σχολικής μονάδας',
    'Failure in deleting school unit' => 'Αποτυχία διαγραφής της σχολικής μονάδας',
    'The school unit was deleted successfully' => 'Η σχολική μονάδα διαγράφηκε επιτυχώς'
];
