<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'sourcePath' => '@app/modules/finance/',
    'languages' => ['el-GR'],
    'translator' => 'Module::t',
    'sort' => false,
    'removeUnused' => true,
    'only' => ['*.php',],
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
    ],
    'format' => 'php',
    'messagePath' => '@app/modules/finance/messages',
    'overwrite' => true,
];