<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create Finance Kae' => '',
    'Create Finance Kaecredit' => '',
    'Create Finance Kaecreditpercentage' => '',
    'Create Finance Supplier' => '',
    'Create Finance Year' => '',
    'Delete' => '',
    'Employer id' => '',
    'Expenditures Management' => 'Διαχείριση Δαπανών',
    'FAX' => '',
    'Finance Kaecreditpercentages' => '',
    'Finance Kaecredits' => '',
    'Finance Kaes' => '',
    'Finance Suppliers' => '',
    'Finance Years' => '',
    'Financial Year Administration' => '',
    'IBAN' => '',
    'Kae ID' => '',
    'Kaecredit ID' => '',
    'Locked Year' => '',
    'Name' => '',
    'No' => '',
    'Phone' => '',
    'RCN' => '',
    'RCN Attribution  Percentage' => '',
    'RCN Attribution Created Date' => '',
    'RCN Attribution Decision' => '',
    'RCN Attribution Percentage ID' => '',
    'RCN Credit Amount' => '',
    'RCN Credit Created Date' => '',
    'RCN Credit ID' => '',
    'RCN Credit Updated Date' => '',
    'RCN Description' => '',
    'RCN Title' => '',
    'RCN Withdrawal Amount' => '',
    'RCN Withdrawal Created Date' => '',
    'RCN Withdrawal Decision' => '',
    'RCN Withdrawal ID' => '',
    'Reset' => '',
    'Save RCN credits' => '',
    'Search' => '',
    'Set RCN Credits' => '',
    'Supplier ID' => '',
    'Tax Office' => '',
    'Tax Office ID' => '',
    'Tax Office Name' => '',
    'Tax Office Prefecture' => '',
    'Update' => '',
    'Update RCΝ credits' => '',
    'Update {modelClass}: ' => '',
    'VAT' => '',
    'Working Year' => '',
    'Year' => '',
    'Year Credit Amount' => '',
    'Yes' => '',
    'lead-currentyear' => '',
    'lead-delete' => '',
    'lead-lock' => '',
    'lead-update' => '',
    'lead-view' => '',
];
