<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'School' => 'Σχολείο',
    'Save and reate new' => 'Αποθήκευση και δημιουργία νέας',
    'Save' => 'Αποθήκευση',
    'Update' => 'Ενημέρωση',    
    'Create' => 'Δημιουργία',
    'Directorate of Education' => 'Διεύθυνση Εκπαίδευσης',
    'School Unit' => 'Σχολείο',
    'Remarks' => 'Παρατηρήσεις',
    'Approval Document Protocol' => 'Πρωτόκολλο Έγκρισης ΠΔΕ',
    'School Directorate Protocol' => 'Πρωτόκολλο Διεύθυνσης Σχολείου',
    'School Record' => 'Πρακτικό Συλλόγου',
    'Class' => 'Τάξη ή Τμήμα',
    'Program' => 'Πρόγραμμα',
    'Date' => 'Ημερομηνία',
    'Description' => 'Σημείωση',
    'Help' => 'Βοήθεια',
    'Error in downloading file.' => 'Σφάλμα στη λήψη του αρχείου.',
    'Archive' => 'Αρχειοθέτηση',
    'Restore' => 'Επαναφορά',
    'Created' => 'Δημιουργήθηκε',
    'Submit' => 'Υποβολή',
    'Export to PDF' => 'Εξαγωγή σε PDF',
    'Error in creating pdf file.' => 'Σφάλμα κατά τη δημιουργία του pdf αρχείου.',
    'PRIMARY' => 'Πρωτοβάθμια',
    'SECONDARY' => 'Δευτεροβάθμια',    
    'Surname' => 'Επίθετο',
    'Name' => 'Όνομα',
    'RegNum' => 'Α.Μ.',
    'Specialisation' => 'Ειδ/τα',
    'Organic Post' => 'Οργανική',    
    'From' => 'Από',
    'To' => 'Μέχρι',
    'Hours' => 'Ώρες',    
    'Actions' => 'Ενέργειες',
    'End of teaching year.' => 'Λήξη διδακτικού έτους.',
    'For ...' => 'Για ...',
    'Duties of Disposed Teachers' => 'Καθήκοντα Εκπαιδευτικού σε Διάθεση',
    'Teachers' => 'Εκπαιδευτικοί',
    'Please select teachers of only one directorate.' => 'Παρακαλώ επιλέξτε εκπαιδευτικούς μόνο μίας Διεύθυνσης.',
    'Error in saving the teacher details in the database.' => 'Σφάλμα κατά την αποθήκευση των στοιχείων του εκπαιδευτικού στη βάση δεδομένων.',
    'Download Decision' => 'Κατέβασμα Απόφασης',
    'The creation of the approval failed, because the template file for the approval does not exist.' => 'Η δημιουργία της έγκρισης απέτυχε επειδή δεν υπάρχει το πρότυπο αρχείο για τη δημιουργία της.',
    'Organic Post Directorate' => 'Δ/νση Οργανικής',
    'Directorate' => 'Δ/νση',
    'View Approval' => 'Προβολή Έγκρισης',
    'Teacher' => 'Εκπαιδευτικός',
    'Donwload file' => '"Κατέβασμα" αρχείου',
    'The suggestion of the directorate was deleted successfully.' => 'Η εισήγηση της Δ/νσης διαγράφηκε επιτυχώς.',
    'The suggestion of the directorate cannot be deleted.' => 'Η εισήγηση της Δ/νσης δεν μπορεί να διαγραφεί.',
    'Local Directorate Suggestions' => 'Εισηγήσεις τοπικών Διευθύνσεων',
    'Create Local Directorate Suggestion' => 'Δημιουργία Εισήγησης Τοπικής Διεύθυνσης',
    'Update Local Directorate Suggestion' => 'Ενημέρωση Εισήγησης Τοπικής Διεύθυνσης',
    'View Local Directorate Suggestion' => 'Προβολή Εισήγησης Τοπικής Διεύθυνσης',
    'Error in downloading file.' => 'Σφάλμα κατά τη μεταφόρτωση του αρχείου.',
    'Directorate Protocol' => 'Πρωτόκολλο',
    'Reason' => 'Λόγος',
    'Select Directorate ...' => 'Επιλέξτε Διεύθυνση ...',
    'The suggestion of the directorate was updated successfully.' => 'Η εισήγηση της διεύθυνσης ενημερώθηκε επιτυχώς.',
    'The update of the suggestion of the directorate failed.' => 'Η ενημέρωση της εισήγησης της διεύθυνσης απέτυχε.',
    'The local directorate decision already exists and not change was applied to it.' => 'Η απόφασης της τοπίκης Διεύθυνσης υπάρχει ήδη και καμία αλλαγή δεν έγινε στα στοιχεία αυτής.',
    'Educational Data' => 'Εκπαιδευτικά Δεδομένα',
    'View/edit/delete teachers' => 'Προβολή/επεξεργασία/διαγραφή εκπαιδευτικών'
];
