<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'School' => 'Σχολείο',
    'Save and reate new' => 'Αποθήκευση και δημιουργία νέας',
    'Save' => 'Αποθήκευση',
    'Update' => 'Ενημέρωση',    
    'Create' => 'Δημιουργία',
    'Directorate of Education' => 'Διεύθυνση Εκπαίδευσης',
    'School Unit' => 'Σχολείο',
    'Remarks' => 'Παρατηρήσεις',
    'Approval Document Protocol' => 'Πρωτόκολλο Έγκρισης ΠΔΕ',
    'School Directorate Protocol' => 'Πρωτόκολλο Διεύθυνσης Σχολείου',
    'School Record' => 'Πρακτικό Συλλόγου',
    'Class' => 'Τάξη ή Τμήμα',
    'Program' => 'Πρόγραμμα',
    'Date' => 'Ημερομηνία',
    'Description' => 'Σημείωση',
    'Forward State' => 'Προώθηση Κατάστασης',
    'Update State' => 'Ενημέρωση Κατάστασης',
    'Forward to State' => 'Προώθηση στην Κατάσταση',
    'Update of State' => 'Ενημέρωση της Κατάστασης ',
    'State' => 'Κατάσταση',
    'Download Decision' => 'Κατέβασμα Απόφασης',
    'Forward to next state' => 'Προώθηση στην επόμενη κατάσταση',
    'Backward to previous state' => 'Μετάβαση στην προηγούμενη κατάσταση',
    'The state was updated successfully.' => 'Η κατάσταση της έγκρισης μετακίνσης ενημερώθηκε επιτυχώς.',
    'View States' => 'Καταστάσεις Έγκρισης Μετακίνησης',
    'Update State Title' => 'Ενημέρωση Κατάστασης Έγκρισης',
    'State Name' => 'Τίτλος Κατάστασης Έγκρισης',
    'Existing file' => 'Υπάρχον αρχείο',
    'Download digitally signed file' => 'Κατεβάστε το ψηφιακά υπογεγραμμένο αρχείο',
    'Digitally Signed File' => 'Ψηφιακά Υπογεγραμμένο Αρχείο',
    'Help' => 'Βοήθεια',
    'Error in downloading file.' => 'Σφάλμα στη λήψη του αρχείου.',
    'Archive' => 'Αρχειοθέτηση',
    'Restore' => 'Επαναφορά',
    'Created' => 'Δημιουργήθηκε',
    'Submit' => 'Υποβολή',
    'Statistics' => 'Στατιστικά',
    'Export to PDF' => 'Εξαγωγή σε PDF',
    'Error in creating pdf file.' => 'Σφάλμα κατά τη δημιουργία του pdf αρχείου.',
    'PRIMARY' => 'Πρωτοβάθμια',
    'SECONDARY' => 'Δευτεροβάθμια',
    'Specialisation' => 'Ειδικότητα',
    'Create Teacher Disposal' => 'Δημιουργία Διάθεσης Εκπαιδευτικού',
    'The teacher disposal was saved successfully.' => 'Η διάθεση εκπαιδευτικού αποθηκεύτηκε επιτυχώς.',
    'Surname' => 'Επίθετο',
    'Name' => 'Όνομα',
    'RegNum' => 'Α.Μ.',
    'Specialisation' => 'Ειδικότητα',
    'Organic Post' => 'Οργανική θέση',
    'Disposal School' => 'Σχολείο Διάθεσης',
    'From' => 'Από',
    'To' => 'Μέχρι',
    'Hours' => 'Ώρες',
    'Actions' => 'Ενέργειες',
    'End of teaching year.' => 'Λήξη διδακτικού έτους.',
    'Create Teacher Disposal' => 'Δημιουργία Διάθεσης Εκπαιδευτικού',
    'Teachers\' Disposals' => 'Διαθέσεις Εκπαιδευτικών',
    'Disposals Approvals' => 'Εγκρίσεις Διαθέσεων',
    'Update Teacher Disposal' => 'Ενημέρωση Διάθεσης Εκπαιδευτικού',
    'View Teacher\'s Disposal' => 'Προβολής Διάθεσης Εκπαιδευτικού',
    'Select disposal hours...' => 'Επιλέξτε ώρες διάθεσης...',
    'Select disposal school...' => 'Επιλέξτε σχολείο διάθεσης...',
    'For ...' => 'Για ...',
    'Disposal Reasons' => 'Λόγοι Διάθεσης Εκπαιδευτικών',
    'Duties of Disposed Teachers' => 'Καθήκοντα Εκπαιδευτικού σε Διάθεση',
    'Teachers' => 'Εκπαιδευτικοί',
    'Disposal Approval States' => 'Καταστάσεις Έγκρισης Διάθεσης',
    'View Disposal Reason' => 'Προβολή Λόγου Διάθεσης',
    'Create Disposal Reason' => 'Δημιουργία Λόγου Διάθεσης',
    'The details of the disposal duty were saved successfully.' => 'Τα στοιχεία των καθηκόντων διάθεσης αποθηκεύτηκαν επιτυχώς',
    'The disposal duty was deleted successfully.' => 'Το καθήκον διάθεσης διαγράφηκε επιτυχώς.',
    'The deletion of the disposal duty failed.' => 'Η διαγραφή του καθήκοντος διάθεσης απέτυχε.',
    'Disposals\' Duties' => 'Καθήκοντα Διαθέσεων',
    'Create Disposal Duty' => 'Δημιουργία Καθήκοντος Διάθεσης',
    'Update Disposal Duty' => 'Ενημέρωση Καθήκοντος Διάθεσης',
    'View Disposal Duty' => 'Προβολή Καθήκοντος Διάθεσης',
    'Create Disposals\' Approval' => 'Δημιουργία Έγκρισης Διαθέσεων',
    'The teacher disposal was deleted successfully.' => 'Η διάθεση εκπαιδευτικού διαγράφηκε επιτυχώς.',
    'Please select at least one disposal.' => 'Παρακαλώ επιλέξτε τουλάχιστον μία διάθεση.',
    'Disposals for Approval' => 'Διαθέσεις προς Έγκριση'
];
