<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this file?' => 'Είστε σίγουροι για τη διαγραφή του αρχείου;',
    'Are you sure you want to download this file?' => 'Είστε σίγουροι για τη μεταφόρτωση του αρχείου;',
    'Create' => 'Δημιουργία',
    'Created At' => 'Δημιουργήθηκε',
    'Delete' => 'Διαγραφή',
    'Deleted' => 'Διαγράφηκε',
    'Download' => 'Μεταφόρτωση',
    'File deleted.' => 'Το αρχείο διαγράφηκε.',
    'Filename' => 'Όνομα αρχείου',
    'ID' => 'Κωδικός',
    'Mime' => 'Mime',
    'Original Filename' => 'Όνομα αρχείου προέλευσης',
    'Size' => 'Μέγεθος',
    'Substitute Teacher Files' => 'Αρχεία δεδομένων',
    'Substitute Teacher Files Upload' => 'Μεταφόρτωση αρχείων δεδομένων',
    'The file was not deleted.' => 'Το αρχείο δεν διαγράφηκε',
    'Title' => 'Τίτλος',
    'Update' => 'Ενημέρωση',
    'Update {modelClass}: ' => 'Ενημέρωση {modelClass}: ',
    'Updated At' => 'Ενημερώθηκε',
    'Upload File' => 'Μεταφόρτωση αρχείου',
    'Upload Substitute Teacher Files' => 'Μεταφόρτωση αρχείων δεδομένων',
];
