<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accompanying documents (certifications, etc.' => 'Συνοδευτικά έγγραφα (βεβαίωση, δήλωση για αναρρωτική, κλπ.',
    'Add Employee' => 'Προσθήκη Εργαζομένου',
    'Address' => 'Διεύθυνση',
    'Application date' => 'Ημερομηνία  αίτησης',
    'Application protocol' => 'Πρωτόκολλο αίτησης',
    'Appointment Date' => 'Ημερομηνία Διορισμού',
    'Appointment FEK' => 'ΦΕΚ Διορισμού',
    'Are you sure you want to delete this item?' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το αντικείμενο;',
    'Are you sure you want to delete this leave?' => 'Είστε βέβαιοι ότι επιθυμείτε να διαγράψετε αυτή την άδεια;',
    'Are you sure you want to delete?' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε;',
    'Are you sure you want to print this leave?' => 'Είστε βέβαιοι ότι επιθυμείτε να εκτυπώσετε αυτή την άδεια;',
    'Choose...' => 'Επιλέξτε',
    'Comment' => '@@Σχόλιο@@',
    'Comments' => 'Σχόλια',
    'Create' => 'Δημιουργία',
    'Create Leave' => 'Δημιουργία άδειας',
    'Create Leave Type' => 'Δημιουργία τύπου άδειας',
    'Create Ts' => 'Δημιουργήθηκε στις',
    'Created At' => 'Δημιουργήθηκε στις',
    'Decision date' => 'Ημερομηνία απόφασης',
    'Decision protocol' => 'Πρωτόκολλο απόφασης',
    'Delete' => 'Διαγραφή',
    'Deleted' => 'Διεγραμμένο',
    'Description' => 'Περιγραφή',
    'Download' => 'Μεταφόρτωση',
    'Duration in days' => 'Διάρκεια σε ημέρες',
    'Edit' => 'Επεξεργασία',
    'Employee' => 'Υπάλληλος',
    'Employees' => 'Εργαζόμενοι',
    'End date' => 'Ημερομηνία λήξης',
    'Father\'s name' => 'Πατρώνυμο',
    'Filename' => 'Όνομα αρχείου',
    'ID' => 'ID',
    'Identification Number' => 'Α.Δ.Ταυτότητας',
    'Leave' => 'Άδεια',
    'Leave Prints' => 'Εκτυπώσεις αδειών',
    'Leave Types' => 'Τύποι αδειών',
    'Leave type' => 'Τύπος άδειας',
    'Leaves' => 'Άδειες',
    'Mobile' => 'Κινητό Τηλ.',
    'Mother\'s name' => 'Μητρώνυμο',
    'Name' => 'Όνομα',
    'No of Doctorate Degrees' => 'Πλήθος Διδακτορικών Τίτλων',
    'No of Master Degrees' => 'Πλήθος Μεταπτυχιακών Τίτλων',
    'Not deleted leaves' => 'Μη διεγραμμένες άδειες',
    'Pay Scale' => 'Μ.Κ.',
    'Pay Scale Date' => 'Ημερομηνία Μ.Κ.',
    'Personal' => 'Προσωπικά',
    'Position' => 'Θέση',
    'Print' => 'Εκτύπωση',
    'Print again' => 'Εκτύπωση ξανά',
    'Print file' => 'Αρχείο εκτύπωσης',
    'Professional' => 'Επαγγελματικά',
    'Protocol date' => 'Ημερομηνία πρωτοκόλλου αίτησης',
    'Rank' => 'Βαθμός',
    'Rank Date' => 'Ημερομηνία Βαθμού',
    'Reason (for special leaves etc.)' => 'Λόγος (για ειδικές κλπ)',
    'Reset' => 'Επαναφορά',
    'Return to view' => 'Επιστροφή στην προβολή',
    'Search' => 'Αναζήτηση',
    'Search deleted employees only' => 'Αναζήτηση μόνο σε διαγραμμένους εργαζόμενους',
    'Service Adoption' => 'Ανάληψη υπηρεσίας',
    'Service Adoption Date' => 'Ημερομηνία Ανάληψης Υπηρεσίας',
    'Service Organic' => 'Οργανική Θέση',
    'Service Serve' => 'Θέση Υπηρέτησης',
    'Social Security Number' => 'Α.Μ.Κ.Α.',
    'Specialisation' => 'Ειδικότητα',
    'Start date' => 'Ημερομηνία έναρξης',
    'Status' => 'Κατάσταση',
    'Succesfully generated file on {date}.' => 'Το αρχείο δημιουργήθηκε με επιτυχία την {date}.',
    'Surname' => 'Επώνυμο',
    'TIN' => 'Α.Φ.Μ.',
    'Telephone' => 'Τηλέφωνο',
    'The print document for the requested leave was not generated.' => 'Το αρχείο εκτύπωσης για την ζητούμενη άδεια δεν δημιουργήθηκε.',
    'The requested leave is deleted.' => 'Η άδεια που ζητήθηκε είναι διεγραμμένη.',
    'This leave is marked as deleted.' => 'Αυτή η άδεια έχει σημανθεί ως διεγραμμένη.',
    'UNKNOWN' => 'ΑΓΝΩΣΤΟ',
    'Update' => 'Ενημέρωση',
    'Update Employee' => 'Επεξεργασία Εργαζομένου',
    'Update Ts' => 'Ημ/νία Μεταβολής',
    'Update leave' => 'Ενημέρωση άδειας',
    'Update {modelClass}: ' => 'Ενημέρωση {modelClass}:',
    'Updated At' => 'Μεταβλήθηκε στις',
    'Work Experience' => 'Προϋπηρεσία',
];
