<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accompanying documents (certifications, etc.' => 'Συνοδευτικά έγγραφα (βεβαίωση, δήλωση για αναρρωτική, κλπ.',
    'Application date' => 'Ημερομηνία  αίτησης',
    'Application protocol' => 'Πρωτόκολλο αίτησης',
    'Are you sure you want to delete this item?' => 'Είστε βέβαιοι ότι επιθυμείτε να διαγράψετε αυτό το αντικείμενο;',
    'Are you sure you want to delete this leave?' => 'Είστε βέβαιοι ότι επιθυμείτε να διαγράψετε αυτή την άδεια;',
    'Are you sure you want to print this leave?' => 'Είστε βέβαιοι ότι επιθυμείτε να εκτυπώσετε αυτή την άδεια;',
    'Comment' => '@@Σχόλιο@@',
    'Comments' => 'Σχόλια',
    'Create Leave' => 'Δημιουργία άδειας',
    'Create Leave Type' => 'Δημιουργία τύπου άδειας',
    'Create Ts' => '',
    'Decision date' => 'Ημερομηνία απόφασης',
    'Decision protocol' => 'Πρωτόκολλο απόφασης',
    'Delete' => 'Διαγραφή',
    'Deleted' => 'Διεγραμμένο',
    'Description' => 'Περιγραφή',
    'Duration in days' => 'Διάρκεια σε ημέρες',
    'Employee' => 'Υπάλληλος',
    'End date' => 'Ημερομηνία λήξης',
    'ID' => 'ID',
    'Leave Types' => 'Τύποι αδειών',
    'Leave type' => 'Τύπος άδειας',
    'Leaves' => 'Άδειες',
    'Name' => 'Όνομα',
    'Not deleted leaves' => 'Μη διεγραμμένες άδειες',
    'Print' => '',
    'Protocol date' => 'Ημερομηνία πρωτοκόλλου αίτησης',
    'Reason (for special leaves etc.)' => 'Λόγος (για ειδικές κλπ)',
    'Reset' => 'Επαναφορά',
    'Search' => 'Αναζήτηση',
    'Start date' => 'Ημερομηνία έναρξης',
    'The requested leave is deleted.' => 'Η άδεια που ζητήθηκε είναι διεγραμμένη.',
    'This leave is marked as deleted.' => 'Αυτή η άδεια έχει σημανθεί ως διεγραμμένη.',
    'Update' => 'Ενημέρωση',
    'Update Ts' => '',
    'Update leave' => 'Ενημέρωση άδειας',
    'Update {modelClass}: ' => 'Ενημέρωση {modelClass}:',
];
