<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administer RCN' => 'Διαχείριση ΚΑΕ',
    'Create/Update/Delete RCN' => 'Δημιουργία/Επεξεργασία/Διαγραφή ΚΑΕ',
    'Attribute percentages of initial RCNs credits of the currently working year' => 'Καθορισμός ποσοστών διάθεσης των πιστώσεων των ΚΑΕ του τρέχοντος έτους.',
    'Percentages of initial RCNs credits' => 'Ποσοστά διάθεσης πιστώσεων ΚΑΕ',
    'Administer Financial Year' => 'Διαχείριση Οικονομικού Έτους',
    'Set RCN credits for the <strong>currently, working</strong> year' => 'Καθορισμός πιστώσεων στους ΚΑΕ του <strong>τρέχοντος</strong> έτους',
    'Year Settings' => 'Ρυθμίσεις Έτους',
    'Create/Update/Delete/Lock/Set Currently Working Year' => 'Δημιουργία/Επεξεργασία/Διαγραφή/Κλείδωμα/Ορισμός ως τρέχον',
    'Update RCΝ credits' => 'Ενημέρωση πιστώσεων ΚΑΕ',
    'RCN Credits' => 'Πιστώσεις ΚΑΕ',
    'Lock' => 'Κλείδωμα',
    'RCN' => 'ΚΑΕ',
    'RCN Credit Amount' => 'Ποσό πίστωσης ΚΑΕ',
    'RCN Credit Created Date' => 'Ημερομηνία πίστωσης ΚΑΕ',
    'RCN Credit ID' => 'ID πίστωσης ΚΑΕ',
    'RCN Credit Updated Date' => 'Ημερομηνία ενημέρωσης πίστωσης ΚΑΕ',
    'Set RCN Credits' => 'Καθορισμός πιστώσεων ΚΑΕ',
    'Unlock' => 'Ξεκλείδωμα',
    'Create Finance Year' => 'Δημιουργία Οικονομικού Έτους',
    'Credit Amount' => 'Ποσό Πίστωσης',
    'Currently Working Year' => 'Τρέχον Έτος Εργασίας',
    'Delete' => 'Διαγραφή',
    'Expenditures Management' => 'Διαχείριση Δαπανών',
    'Failed locking financial year' => 'Αποτυχία κλειδώματος του οικομομικού έτους',
    'Failed unlocking financial year' => 'Αποτυχία ξεκλειδώματος του οικομομικού έτους',
    'Finance Years' => 'Οικονομικά Έτη',
    'Financial Year Administration' => 'Διαχείριση Οικονομικού Έτους',
    'Locked Year' => 'Κλειδωμένο Έτος',
    'No' => 'Όχι',
    'Set as currently working' => 'Ορισμός ως τρέχον έτος εργασίας',
    'The financial year {id} was locked succesfully.' => 'Το οικονομικό έτος {id} κλειδώθηκε επιτυχώς.',
    'The financial year {id} was unlocked succesfully.' => 'Το οικονομικό έτος {id} ξεκλειδώθηκε επιτυχώς.',
    'The sum of credits for the RCN is not equal to the credit attributed for year {year}. Please correct to continue.' => 'Το άθροισμα των πιστώσεων των ΚΑΕ δεν συμφωνεί με την πίστωση για το έτος {year} Παρακαλώ διορθώστε για να προχωρήσετε.',
    'Update' => 'Ενημέρωση',
    'View' => 'Προβολή',
    'Year' => 'Έτος',
    'Yes' => 'Ναι',
    'Your action did not complete succesfull. There was an error during saving in the database.' => 'H ενέργειά σας δεν ολοκληρώθηκε με επιτυχία. Υπήρξε σφάλμα κατά την αποθήκευση στη βάση δεδομένων.',
    'Your choices cannot be carried out, because the financial year is locked.' => 'Οι επιλογές σας δεν μπορούν να πραγματοποιηθούν επειδή το έτος είναι κλειδωμένο.',
    'Your choices were succesfully saved.' => 'Οι επιλογές σας αποθηκεύτηκαν επιτυχώς.',
];
